version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: app
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
  app:
    build: ./
    tty: true
    ports:
      - 8080:8080
    links:
      - db

volumes:
  db_vol:
